CREATE DATABASE IF NOT EXISTS railway_dbms;
USE railway_dbms;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  user_type VARCHAR(40) NOT NULL DEFAULT 'Admin',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trains (
  id INT AUTO_INCREMENT PRIMARY KEY,
  train_number VARCHAR(30) UNIQUE NOT NULL,
  train_name VARCHAR(120) NOT NULL,
  source VARCHAR(120) NOT NULL,
  destination VARCHAR(120) NOT NULL,
  capacity INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  station_code VARCHAR(20) UNIQUE NOT NULL,
  station_name VARCHAR(120) NOT NULL,
  city VARCHAR(90) NOT NULL,
  state VARCHAR(90) NOT NULL,
  platforms INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS routes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  route_code VARCHAR(30) UNIQUE NOT NULL,
  route_name VARCHAR(120) NOT NULL,
  source_station VARCHAR(120) NOT NULL,
  destination_station VARCHAR(120) NOT NULL,
  distance_km INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schedules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  train_id INT NOT NULL,
  route_id INT NOT NULL,
  arrival_time VARCHAR(10) NOT NULL,
  departure_time VARCHAR(10) NOT NULL,
  platform_number VARCHAR(20) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (train_id) REFERENCES trains(id),
  FOREIGN KEY (route_id) REFERENCES routes(id)
);

CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employee_code VARCHAR(30) UNIQUE NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  role VARCHAR(80) NOT NULL,
  department VARCHAR(80) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(120) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  report_type VARCHAR(40) NOT NULL,
  generated_by VARCHAR(80) NOT NULL,
  export_format VARCHAR(20) NOT NULL,
  generated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
